#!/bin/bash
# check if a file 

if [ -e $HOME ]
then
	echo "The object exists, is it a file?"
	if [ -f $HOME ]
	then
		echo "YES, it's a file!!"
	else
		echo "NO, it'\s not a file!!"
		if [ -f $HOME/.bash_history ]
		then 
			echo "BUT this is a file!!"
		fi
	fi
else
	echo "Sorry, the object doesn't exist"
fi

